### ISSUE TITLE
Error during installation 

### ISSUE THREAD

**Issue by skaftanis** [woanware/usbdeviceforensics#5]
Hi, I am trying to install this on Windows 10 but I get this error on python setup.py build

```
running build
running build_exe
Traceback (most recent call last):
  File "setup.py", line 11, in <module>
    executables = [Executable("usbdeviceforensics.py")])
  File "C:\Users\Public\Anaconda3\lib\site-packages\cx_Freeze\dist.py", line 349, in setup
    distutils.core.setup(**attrs)
  File "C:\Users\Public\Anaconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\Public\Anaconda3\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Users\Public\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\Public\Anaconda3\lib\distutils\command\build.py", line 135, in run
    self.run_command(cmd_name)
  File "C:\Users\Public\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\Public\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\Public\Anaconda3\lib\site-packages\cx_Freeze\dist.py", line 219, in run
    freezer.Freeze()
  File "C:\Users\Public\Anaconda3\lib\site-packages\cx_Freeze\freezer.py", line 615, in Freeze
    self.finder = self._GetModuleFinder()
  File "C:\Users\Public\Anaconda3\lib\site-packages\cx_Freeze\freezer.py", line 341, in _GetModuleFinder
    finder.IncludePackage(name)
  File "C:\Users\Public\Anaconda3\lib\site-packages\cx_Freeze\finder.py", line 653, in IncludePackage
    module = self._ImportModule(name, deferredImports)
  File "C:\Users\Public\Anaconda3\lib\site-packages\cx_Freeze\finder.py", line 350, in _ImportModule
    raise ImportError("No module named %r" % name)
ImportError: No module named 'Registry'
```

I use  cx-Freeze-5.1

**Comment by woanware** [comment]
You need the "registry" library which is mentioned in the readme
